### ISSUE TITLE
사용자 로그인 이후 CRUD 과정에서 비밀번호 검증 과정 논의

### ISSUE THREAD

**Issue by JangCoding** [LSW990918/BackOffice#4]
1. request 통해 password 를 다시 입력받고 현재 토큰에 저장된 값과 비교

2. param 통해 password 를 다시 입력받고 현재 토큰에 저장된 값과 비교

3. 로그인 되어있는 상태라면 password 를 다시 입력받지 않고 토큰을 통해 비교

**Comment by LSW990918** [comment]
1. 지금 그대로 써도 되는게 장점 하지만 보통은 딜리트매핑시에 리퀘스트바디를 따로 받지 않는다.
2. 비밀번호만 알고있다면 작성자가 아니더라도 삭제나 수정 가능 장점이자 단점
3. 보안등급이 높을것 같지만 지금 바로는 구현을 하지못하고 토큰이 완성되고 난후 작성 가능

**Comment by hyunzoo123123** [comment]
3333 보안! 토큰 관리만 잘 된다면 사용성도 좋을 것 같아요!

**Comment by JangCoding** [comment]
요구사항에 비밀번호를 다시 한 번 입력받아야 하는 의무는 비밀번호 변경시에만 포함되므로
사용자 인증/인가가 되어있다면 다시 비밀번호를 입력하는 과정 없이 토큰값을 확인하여 
유저 id , password 비교를 통해 진행하는 것으로 결정
